### ISSUE TITLE
Use list-group instead of btn-group-vertical

### ISSUE THREAD

**Issue by jerguslejko** [kristiankostecky/makes-money-all-the-time#1]
Using `.btn-group-vertical` in this case is not ideal.

Instead try using `.list-group` (and `.list-group-item` respectively) which is meant to be used in situations like these.

Also, do not mix-up `.col-*-*` with any other classes. Rather prefer element nesting:

*BAD*
```html
<div class="col-sm-6 list-group">
    <button class="list-group-item"></button>
</div>
```

*GOOD*
```html
<div class="col-sm-6">
    <div class="list-group">
        <a href="#" class="list-group-item">...</a>
    </div>
</div>

```

**Comment by kristiankostecky** [comment]
Resolved in 49cb47e
