### ISSUE TITLE
Prefer local files over ones on CDNs

### ISSUE THREAD

**Issue by jerguslejko** [kristiankostecky/makes-money-all-the-time#2]
Heya!

You got _bootstrap_ installed but you're loading `bootstrap.js` from the CDN. please fix 🌵

**Comment by kristiankostecky** [comment]
Hi there!
In task is written to link dependencies from CDNs, so I'm not sure if I should use CDN for all dependencies  and uninstall bootstrap or just use it normally with installed bootstrap. What do you think?

**Comment by jerguslejko** [comment]
Well, if the task says so, use CDNs 🍕
