### ISSUE TITLE
6:6 does not quite cut it. 3:9 might be better

### ISSUE THREAD

**Issue by jerguslejko** [kristiankostecky/makes-money-all-the-time#3]
Try making left-sided navigation little thinner. I think `3:9` would work very well. 💻

**Comment by kristiankostecky** [comment]
Resolved in 19af87d

**Comment by jerguslejko** [comment]
Actually, you do not need those `.col-xs-12` as `.col-sm-*` applies only to screens same or wider than *sm* and `<div>` is 100% by default...

**Comment by kristiankostecky** [comment]
Resolved in 341ab7b
